#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|ts|jsx|tsx|json|css|scss|md|html)$' || true)


if [ -n "$FILES" ]; then
	echo "arquivos formatados:"
	echo "$Files"
	echo "$FILES" | xargs npx prettier --write
	echo "$FILES" | xargs git add
	pnpm typecheck
	pnpm test
	pnpm lint
fi
